### ISSUE TITLE
NameError: name 'file' is not defined

### ISSUE THREAD

**Issue by liut0012** [jaeyoon1603/Retrieval-RegionalAttention#1]
Dear Jaeyoon, while testing with the script Test_OxfordParis.py, I encounter the following error. Do you know the reason? 

$ python Test_OxfordParis.py --dataset Oxford
Traceback (most recent call last):
  File "Test_OxfordParis.py", line 334, in <module>
    dataset = Dataset(dataset_path, eval_binary)
  File "Test_OxfordParis.py", line 218, in __init__
    self.load()
  File "Test_OxfordParis.py", line 238, in load
    q_data = file("{0}/{1}".format(self.lab_root, e)).readline().split(" ")
NameError: name 'file' is not defined

**Comment by jaeyoon1603** [comment]
Hello liut0012,
It can be caused by Python version and the code was written on Python 2. 
If you are using Python 3, you can use open() instead of file().


Thanks,

**Comment by liut0012** [comment]
Dear Jaeyoon, That solves the problem. Thanks a lot!
