### ISSUE TITLE
There is a little bug in Test_OxfordParis.py and Common.py

### ISSUE THREAD

**Issue by peace-zy** [jaeyoon1603/Retrieval-RegionalAttention#2]
I am interested in your work，so I want to run the demo.
When I run the test script 
"python Test_OxfordParis.py --dataset Oxford"

That raises a error:

File "xxx/Retrieval-RegionalAttention/Common.py", line 132, in forward
    batch_ind = int(roi[0].data[0])
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number'

I rewrite it as "batch_ind = int(roi.data[0])" in Common.py and Test_OxfordParis.py.
The demo can be run successfully.

**Comment by jaeyoon1603** [comment]
Thank you for your kindness!
It may occur if using Python 3.0 because the project was coded with Python 2.0
